// <auto-generated />
namespace PE.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Initial_DB_Ssetup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initial_DB_Ssetup));
        
        string IMigrationMetadata.Id
        {
            get { return "201910031038124_Initial_DB_Ssetup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
