// <auto-generated />
namespace projW.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class v022 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v022));
        
        string IMigrationMetadata.Id
        {
            get { return "201910171121429_v0.2.2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
